name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:          
    - uses: actions/checkout@v3
    - name: Create .env file
      run: |
          touch .env
          echo TEST_MONGO_URL=mongodb://127.0.0.1:27017 >> .env
          cat .env
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Create mongo Docker container
      id: build_mongo_docker
      uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
          
    - name: Test mongo connection
      id: test_mongo_connection
      run: "sudo mongo localhost:27017"
    
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
